########################################
### CONFIG
########################################

@base = http://localhost:3000/api/v1
@username = sooraj
@password = secret123


########################################
### STATUS — health check
########################################

GET {{base}}/status


########################################
### REGISTER — create user
########################################

POST {{base}}/auth/register
Content-Type: application/json

{
  "username": "{{username}}",
  "password": "{{password}}"
}


########################################
### LOGIN — get JWT
########################################

# @name login
POST {{base}}/auth/login
Content-Type: application/json

{
  "username": "{{username}}",
  "password": "{{password}}"
}


########################################
### CAPTURE TOKEN
########################################

@token = {{login.response.body.token}}


########################################
### AUTH CHECK — protected route test
########################################

GET {{base}}/carriers/ups/connect
Authorization: Bearer {{token}}


########################################
### OAUTH CALLBACK — simulate UPS redirect
########################################

GET {{base}}/carriers/ups/callback?code=fake_addddduffh_code_042e6ffffdec-74d0-444c-bf0d-5b2d9ce5560b&state=1acb7e8e-d6ggg0c-42fe-84c3-f83b2a64e65c


########################################
### rate
########################################

POST {{base}}/rates
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "carrier": "ups",
  "shipper": {
    "city": "NYC",
    "state": "NY",
    "postalCode": "10001",
    "countryCode": "US"
  },
  "shipTo": {
    "city": "LA",
    "state": "CA",
    "postalCode": "90001",
    "countryCode": "US"
  },
  "pkg": {
    "weight": 2,
    "length": 10,
    "width": 8,
    "height": 6
  }
}
